services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: marketing_request_app
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - APP_NAME=MarCom Request
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=http://localhost:8084
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=marketing_request
      - SESSION_DRIVER=database
      - QUEUE_CONNECTION=database
      - APP_KEY=${APP_KEY}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - marketing-network

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8084:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - marketing-network

  db:
    image: mysql:8.0
    ports:
      - "3310:3306"
    environment:
      MYSQL_DATABASE: marketing_request
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - marketing-network

networks:
  marketing-network:
    driver: bridge

volumes:
  db_data:
